### ISSUE TITLE
verses

### ISSUE THREAD

**Issue by christiankaye** [sm1th/mycroft-skill-bible#2]
I started using the Bible Skill and it works very well for speaking the verse of the day. 

Should I be able to tell Mycroft to read certain Bible verses? When I say "get passage, John 3:16" Mycroft does not understand.

**Comment by josmithua** [comment]
Hey there! I'm surprised this skill still works since it's been 3 years since I worked on this! 

The skill currently only speaks the verse of the day.

I currently don't have plans to work on this any further, but feel free to fork my repo and work on it yourself!

God bless,
Joshua
